apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: s3manager-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: s3manager
    namespace: default
roleRef:
  kind: Role
  name: s3manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3manager
  template:
    metadata:
      labels:
        app: s3manager
    spec:
      serviceAccountName: s3manager
      containers:
        - name: s3manager
          image: cloudlena/s3manager:v0.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: "ENDPOINT"
              value: "storage.yandexcloud.net"
            - name: "SKIP_SSL_VERIFICATION"
              value: "true"
            - name: "ACCESS_KEY_ID"
              value: "ACCESS_KEY_ID"  # Замените на реальный ключ
            - name: "SECRET_ACCESS_KEY"
              value: "SECRET_ACCESS_KEY"  # Замените на реальный секрет
---
apiVersion: v1
kind: Service
metadata:
  name: s3manager
spec:
  selector:
    app: s3manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3manager
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: s3manager.apatsev.org.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3manager
                port:
                  number: 80
